README.md, composer.json, composer.lock, src/Faker/GeneratorTrait.php, test/Faker/GeneratorTraitTest.php
=> Enhancement: Implement GeneratorTrait

.travis.yml
=> Fix: Coverage generation

src/Faker/Generator.php, src/Faker/GeneratorTrait.php, src/Faker/Provider/Color.php, test/Faker/GeneratorTest.php, test/Faker/GeneratorTraitTest.php, test/Faker/Provider/ColorTest.php
=> Enhancement: Implement Color provider

composer.json, composer.lock
=> Fix: Add a few relevant keywords

README.md
=> Fix: Add reference to fzaninotto/faker

.php_cs, src/Faker/Generator.php, src/Faker/GeneratorTrait.php, src/Faker/Provider/Color.php, src/PHPUnit/BuildsMockTrait.php, test/Faker/GeneratorTest.php, test/Faker/GeneratorTraitTest.php, test/Faker/Provider/ColorTest.php, test/PHPUnit/BuildsMockTraitTest.php
=> Fix: Specify file level header

src/DataProvider/DataProviderInterface.php, src/DataProvider/InvalidString.php, test/DataProvider/InvalidStringTest.php
=> Enhancement: Implement InvalidString data provider

src/DataProvider/InvalidString.php
=> Fix: Keep sorted

src/DataProvider/InvalidBoolean.php, test/DataProvider/InvalidBooleanTest.php
=> Invalid boolean provider

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
This PR
:information_desk_person: For reference, see https://github.com/blog/2111-issue-and-pull-request-templates.
=> Enhancement: Leverage GitHub issue and PR template capabilities

test/DataProvider/InvalidBooleanTest.php, test/DataProvider/InvalidStringTest.php
=> Fix: Streamline data provider tests

src/DataProvider/InvalidUuid.php, test/DataProvider/InvalidUuidTest.php
=> Enhancement: Implement InvalidUuid data provider

src/DataProvider/InvalidInteger.php, test/DataProvider/InvalidIntegerTest.php
=> Enhancement: Implement InvalidInteger data provider

src/DataProvider/InvalidBoolean.php, src/DataProvider/InvalidString.php, src/DataProvider/InvalidUuid.php
=> Fix: Docblock

README.md
=> Fix: Update README.md with note about data providers

.travis.yml, composer.json, composer.lock
=> Enhancement: Update phpunit/phpunit

README.md, composer.json, composer.lock
=> Fix: Update README.md and composer.json

test/Faker/GeneratorTest.php, test/Faker/GeneratorTraitTest.php
=> Fix: Rename variable

src/DataProvider/DataProviderInterface.php, src/DataProvider/DataProviderTrait.php, src/DataProvider/InvalidBoolean.php, src/DataProvider/InvalidFloat.php, src/DataProvider/InvalidInteger.php, src/DataProvider/InvalidNumeric.php, src/DataProvider/InvalidScalar.php, src/DataProvider/InvalidString.php, src/Faker/GeneratorTrait.php, test/DataProvider/DataProviderTraitTest.php, test/DataProvider/InvalidUrlTest.php, test/DataProvider/InvalidUuidTest.php, test/Faker/GeneratorTest.php, test/Faker/GeneratorTraitTest.php
=> Fix: Do not import classes from root namespace

README.md, src/DataProvider/Boolean.php, test/DataProvider/BooleanTest.php
=> Enhancement: Implement Boolean data provider

test/DataProvider/BooleanTest.php
=> Fix: Test method name

README.md, src/DataProvider/Scalar.php, test/DataProvider/ScalarTest.php
=> Enhancement: Implement Scalar data provider

README.md, src/DataProvider/DataProviderTrait.php, test/DataProvider/DataProviderFake.php, test/DataProvider/DataProviderTraitTest.php
=> Enhancement: Allow to compose data providers with provideDataFrom()

README.md, src/DataProvider/Elements.php, test/DataProvider/ElementsTest.php
=> Enhancement: Implement Elements data provider

src/DataProvider/BlankString.php, src/DataProvider/Boolean.php, src/DataProvider/InvalidBoolean.php, src/DataProvider/InvalidFloat.php, src/DataProvider/InvalidInteger.php, src/DataProvider/InvalidIsoDate.php, src/DataProvider/InvalidNumeric.php, src/DataProvider/InvalidScalar.php, src/DataProvider/InvalidString.php, src/DataProvider/InvalidUrl.php, src/DataProvider/InvalidUuid.php, src/DataProvider/Scalar.php
=> Enhancement: Add keys to values

README.md, src/DataProvider/InvalidIntegerish.php, src/DataProvider/InvalidIntegerishNotNull.php, test/DataProvider/InvalidIntegerishNotNullTest.php, test/DataProvider/InvalidIntegerishTest.php
=> Enhancement: Implement InvalidIntegerish data provider

composer.json, composer.lock, phpunit.xml
This PR
💁‍♂️ For reference, see https://github.com/sebastianbergmann/phpunit/compare/5.4.2...5.6.1.
=> Enhancement: Update phpunt/phpunit

README.md, composer.json, composer.lock, src/TestHelper.php, test/DataProvider/AbstractTestCase.php
=> Enhancement: Extract assertImplementsInterface() assertion

README.md, src/TestHelper.php, test/Asset/Foo.php, test/TestHelperTest.php
=> Enhancement: Implement assertFinal() assertion

.codeclimate.yml, README.md
=> Enhancement: Switch to Code Climate platform

composer.json
=> Fix: Author name

README.md, src/TestHelper.php, test/Asset/Bar.php, test/TestHelperTest.php
=> Enhancement: Implement assertExtends() assertion

src/DataProvider/InvalidBoolean.php, src/DataProvider/InvalidFloat.php, src/DataProvider/InvalidInteger.php, src/DataProvider/InvalidIntegerish.php, src/DataProvider/InvalidString.php, src/DataProvider/Scalar.php
=> Fix: Remove element of surprise

README.md, src/DataProvider/Falsy.php, test/DataProvider/FalsyTest.php
=> Enhancement: Implement Falsy data provider

composer.json
This PR
💁‍♂️ For reference, see https://github.com/codeclimate/php-test-reporter/compare/v0.3.2...v0.4.0.
=> Enhancement: Update codeclimate/php-test-reporter

composer.json
This PR
💁‍♂️ For reference, see https://github.com/beberlei/assert/compare/v2.6.5...v2.7.1.
=> Enhancement: Update beberlei/assert

composer.json
=> Fix: Remove obsolete maintainer

README.md, src/TestHelper.php, test/Asset/Satisfy/Foo.php, test/TestHelperTest.php
=> Enhancement: Extract assertClassesSatisfy() assertion

composer.json
This PR
💁‍♂️ For reference, see https://github.com/refinery29/php-cs-fixer-config/compare/0.6.7...0.6.11.
=> Fix: Update refinery29/php-cs-fixer-config

composer.json, src/Faker/Provider/Color.php, src/TestHelper.php
This PR
💁‍♂️ For reference, see https://github.com/refinery29/php-cs-fixer-config/compare/0.6.11...0.6.15.
=> Enhancement: Update refinery29/php-cs-fixer-config

composer.json
This PR
💁‍♂️ For reference, see https://github.com/codeclimate/php-test-reporter/compare/v0.4.0...v0.4.4.
=> Fix: Update codeclimate/php-test-reporter

.travis.yml, Makefile, composer.json
This PR
💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#preferred-install.
=> Fix: Configure preferred installation source in composer.json

src/DataProvider/BlankString.php, src/DataProvider/Boolean.php, src/DataProvider/Falsy.php, src/DataProvider/InvalidBoolean.php, src/DataProvider/InvalidFloat.php, src/DataProvider/InvalidInteger.php, src/DataProvider/InvalidIntegerish.php, src/DataProvider/InvalidIsoDate.php, src/DataProvider/InvalidNumeric.php, src/DataProvider/InvalidScalar.php, src/DataProvider/InvalidString.php, src/DataProvider/InvalidUrl.php, src/DataProvider/InvalidUuid.php, src/DataProvider/Scalar.php, src/DataProvider/Truthy.php
=> Fix: Sort by key

composer.json
=> Fix: Remove stability configuration

composer.json, src/DataProvider/Falsy.php, src/DataProvider/InvalidBoolean.php, src/DataProvider/InvalidFloat.php, src/DataProvider/InvalidInteger.php, src/DataProvider/InvalidIntegerish.php, src/DataProvider/InvalidNumeric.php, src/DataProvider/InvalidScalar.php, src/DataProvider/InvalidString.php, src/DataProvider/Scalar.php
This PR
💁‍♂️ For reference, see 
* https://github.com/beberlei/assert/compare/v2.7.1...v2.7.3
* https://github.com/beberlei/assert/issues/206
=> Enhancement: Add more cases

test/TestHelperTest.php
=> Fix: Remove unused import

README.md, src/DataProvider/InvalidJsonString.php, test/DataProvider/InvalidJsonStringTest.php
=> Enhancement: Add InvalidJsonString data provider

README.md, src/DataProvider/EmptyValue.php, test/DataProvider/EmptyValueTest.php
=> Enhancement: Implement EmptyValue data provider

src/TestHelper.php
This PR
Somewhat related to #174.
💁‍♂️ Not supporting HHVM, so not an issue.
=> Fix: Add type-hint
