refinery29/test-util

- test/Faker/GeneratorTraitTest.php
> Fix: Namespace

- src/Faker/GeneratorTrait.php
> Fix: Remove import

- .travis.yml
- composer.json
- composer.lock
- test/Faker/GeneratorTest.php
- test/Faker/GeneratorTraitTest.php
> Fix: Require only PHP5.3

- .travis.yml
- composer.json
- composer.lock
> Fix: Drop support for PHP5.4

- .travis.yml
- Makefile
- composer.json
- composer.lock
This PR
:information_desk_person: For reference, see https://github.com/refinery29/php-cs-fixer-config/compare/0.2.2...0.4.1.
> Fix: Update refinery29/php-cs-fixer-config

- composer.json
- composer.lock
> Fix: Allow to use phpunit/phpunit:^5.2.3

- .travis.yml
> Fix: Run build using highest dependencies available

- CONTRIBUTING.md
- Makefile
> Fix: Make it first target

- src/Faker/GeneratorTrait.php
- test/Faker/GeneratorTraitTest.php
> Fix: Allow to retrieve Faker statically

- composer.json
- composer.lock
- src/DataProvider/InvalidUrl.php
- test/DataProvider/InvalidUrlTest.php
This PR
Follows #21.
:information_desk_person: The idea is to make generic data providers reusable!
> Enhancement: Implement InvalidUrl provider

- LICENSE
- README.md
This PR
:person_with_pouting_face: It is referred to in file headers, but is actually missing.
> Fix: Add missing licence

- src/DataProvider/AbstractDataProvider.php
- src/DataProvider/InvalidBoolean.php
- src/DataProvider/InvalidString.php
- src/DataProvider/InvalidUrl.php
This PR
:person_with_pouting_face: Since we're not limited to PHP7, we can't yield from other generators, so this provides a way of extending providers (saves duplication, right)?
> Enhancement: Extract AbstractDataProvider

- .github/CONDUCT.md
- README.md
> Fix: Add missing code of conduct

- src/DataProvider/InvalidUrl.php
This PR
:person_with_pouting_face: No need to repeat the same things, right?
> Fix: Let InvalidUrl extend from InvalidString

- src/DataProvider/InvalidFloat.php
- test/DataProvider/InvalidFloatTest.php
> Enhancement: Implement InvalidFloat data provider

- src/DataProvider/DataProviderInterface.php
This PR
:information_desk_person: Who cares if a `Generator` (or an `Iterator`) is returned as long as we can traverse through the return value?
> Fix: Broaden allowed return values

- src/DataProvider/AbstractDataProvider.php
- src/DataProvider/DataProviderTrait.php
- test/DataProvider/DataProviderTraitTest.php
This PR
:information_desk_person: The idea is not having to repeat ourselves too much when we want to make use of data providers.
> Enhancement: Extract DataProviderTrait

- src/Faker/Provider/Color.php
> Fix: Hexadecimal color with Alpha should actually have 4 bytes

- src/Faker/GeneratorTrait.php
- test/Faker/GeneratorTraitTest.php
> Enhancement: Allow to specify locale when fetching Faker\Generator

- test/DataProvider/InvalidBooleanTest.php
- test/DataProvider/InvalidFloatTest.php
- test/DataProvider/InvalidIntegerTest.php
- test/DataProvider/InvalidStringTest.php
> Fix: Do not use assertions to assert invalidity of values

- src/DataProvider/BlankString.php
- test/DataProvider/BlankStringTest.php
> Enhancement: Implement BlankString data provider

- src/DataProvider/InvalidNumeric.php
- test/DataProvider/InvalidNumericTest.php
> Enhancement: Implement InvalidNumeric data provider

- composer.json
- composer.lock
This PR
💁 Without it, the data providers do not work.
> Fix: Require, do not suggest fzaninotto/faker

- src/DataProvider/InvalidScalar.php
- test/DataProvider/InvalidScalarTest.php
> Enhancement: Implement InvalidScalar data provider

- .travis.yml
- composer.json
- composer.lock
This PR
💁 It's dead, and it allows to update `phpunit/phpunit` and to deprecate the `BuildsMocksTrait`.
> Fix: Drop support for PHP 5.5

- test/DataProvider/InvalidUrlTest.php
- test/DataProvider/InvalidUuidTest.php
- test/Faker/GeneratorTraitTest.php
> Fix: Use expectedException() instead of deprecated setExpectedException()

- composer.json
> Fix: Remove suggestion in regard to BuildsMocksTrait

- test/Faker/GeneratorTraitTest.php
> Fix: Use expectExceptionMessage()

- test/Faker/GeneratorTest.php
- test/Faker/GeneratorTraitTest.php
> Fix: Use class keyword

- test/DataProvider/AbstractDataProviderTestCase.php
- test/DataProvider/BlankStringTest.php
- test/DataProvider/InvalidBooleanTest.php
- test/DataProvider/InvalidFloatTest.php
- test/DataProvider/InvalidIntegerTest.php
- test/DataProvider/InvalidNumericTest.php
- test/DataProvider/InvalidScalarTest.php
- test/DataProvider/InvalidStringTest.php
- test/DataProvider/InvalidUrlTest.php
- test/DataProvider/InvalidUuidTest.php
This PR
Related to #64.
💁 This should help with the tests for the PR referenced above.
> Fix: Extract AbstractDataProviderTestCase

- README.md
- src/DataProvider/InvalidBooleanNotNull.php
- src/DataProvider/InvalidFloatNotNull.php
- src/DataProvider/InvalidIntegerNotNull.php
- src/DataProvider/InvalidNumericNotNull.php
- src/DataProvider/InvalidScalarNotNull.php
- src/DataProvider/InvalidStringNotNull.php
- src/DataProvider/InvalidUrlNotNull.php
- src/DataProvider/InvalidUuidNotNull.php
- src/DataProvider/NotNull.php
- test/DataProvider/InvalidBooleanNotNullTest.php
- test/DataProvider/InvalidFloatNotNullTest.php
- test/DataProvider/InvalidIntegerNotNullTest.php
- test/DataProvider/InvalidNumericNotNullTest.php
- test/DataProvider/InvalidScalarNotNullTest.php
- test/DataProvider/InvalidStringNotNullTest.php
- test/DataProvider/InvalidUrlNotNullTest.php
- test/DataProvider/InvalidUuidNotNullTest.php
- test/DataProvider/NotNull.php
This PR
```
/**
* @param string|null $value
*/
function foo($value)
{
Assertion::nullOrString($value);
// does something
}
/**
* @dataProvider Refinery29\Test\Util\DataProvider\InvalidStringWithoutNull::data()
* 
* @param mixed $value
*/
public function testFoo($value)
{
$this->expectException(\InvalidArgumentException::class);
foo($value);
}
```
> Enhancement: Create variations of data providers which do not provide null

- README.md
- src/DataProvider/InvalidIsoDate.php
- src/DataProvider/InvalidIsoDateNotNull.php
- test/DataProvider/InvalidIsoDateNotNullTest.php
- test/DataProvider/InvalidIsoDateTest.php
This PR
Following: https://github.com/refinery29/zeppelin/pull/885/files#r72115858
> Enhancement: Add InvalidIsoDate data provider

- src/DataProvider/AbstractDataProvider.php
> Fix: Mark data() as final

- src/DataProvider/DataProviderTrait.php
This PR
💁 The intention of the trait is to be used from *within* the context of a test case, so reducing the visibility should not break any tests, but reduce the API.
> Fix: Reduce visibility of provideData from public to protected

- README.md
- test/DataProvider/BlankStringTest.php
- test/DataProvider/BooleanTest.php
- test/DataProvider/InvalidBooleanNotNullTest.php
- test/DataProvider/InvalidBooleanTest.php
- test/DataProvider/InvalidFloatNotNullTest.php
- test/DataProvider/InvalidFloatTest.php
- test/DataProvider/InvalidIntegerNotNullTest.php
- test/DataProvider/InvalidIntegerTest.php
- test/DataProvider/InvalidIsoDateNotNullTest.php
- test/DataProvider/InvalidIsoDateTest.php
- test/DataProvider/InvalidNumericNotNullTest.php
- test/DataProvider/InvalidNumericTest.php
- test/DataProvider/InvalidScalarNotNullTest.php
- test/DataProvider/InvalidScalarTest.php
- test/DataProvider/InvalidStringNotNullTest.php
- test/DataProvider/InvalidStringTest.php
- test/DataProvider/InvalidUrlNotNullTest.php
- test/DataProvider/InvalidUrlTest.php
- test/DataProvider/InvalidUuidNotNullTest.php
- test/DataProvider/InvalidUuidTest.php
- test/DataProvider/ScalarTest.php
- test/Faker/GeneratorTraitTest.php
This PR
💁 `phpunit/phpunit` doesn't seem to care, but PHPStorm complains.
> Fix: Prepend slash when referencing data providers

- README.md
> Fix: Examples in README.md

- Makefile
- phpunit.xml
> Fix: Configure columns via phpunit.xml

- src/DataProvider/InvalidIsoDate.php
- test/DataProvider/InvalidIsoDateNotNullTest.php
- test/DataProvider/InvalidIsoDateTest.php
This PR
See: http://php.net/manual/en/class.datetime.php
```
Note: This format is not compatible with ISO-8601, but is left this way for backward compatibility reasons. Use DateTime::ATOM or DATE_ATOM for compatibility with ISO-8601 instead.
```
> Bugfix: Switch to DATE_ATOM

- src/DataProvider/AbstractDataProvider.php
- src/DataProvider/BlankString.php
- src/DataProvider/Boolean.php
- src/DataProvider/DataProviderInterface.php
- src/DataProvider/InvalidBoolean.php
- src/DataProvider/InvalidBooleanNotNull.php
- src/DataProvider/InvalidFloat.php
- src/DataProvider/InvalidFloatNotNull.php
- src/DataProvider/InvalidInteger.php
- src/DataProvider/InvalidIntegerNotNull.php
- src/DataProvider/InvalidIsoDate.php
- src/DataProvider/InvalidIsoDateNotNull.php
- src/DataProvider/InvalidNumeric.php
- src/DataProvider/InvalidNumericNotNull.php
- src/DataProvider/InvalidScalar.php
- src/DataProvider/InvalidScalarNotNull.php
- src/DataProvider/InvalidString.php
- src/DataProvider/InvalidStringNotNull.php
- src/DataProvider/InvalidUrl.php
- src/DataProvider/InvalidUrlNotNull.php
- src/DataProvider/Scalar.php
This PR
💁 The method `data()` is still provided by `AbstractDataProvider`, and the idea of exposing `values()` is to make it easier to compose data providers.
> Fix: Make values() part of the DataProviderInterface

- src/DataProvider/DataProviderTrait.php
- test/DataProvider/DataProviderTraitTest.php
This PR
💁 This allows to specify keys, which in turn could be helpful when tests fail.
> Enhancement: Yield value with associated key

- src/DataProvider/DataProviderTrait.php
- src/Faker/GeneratorTrait.php
> Bugfix: Fix incorrect doc block

- src/DataProvider/InvalidFloat.php
- src/DataProvider/InvalidInteger.php
- src/DataProvider/InvalidString.php
- src/DataProvider/Scalar.php
> Fix: Use false and true

- test/TestHelperTest.php
This PR
💁‍♂️ Because we should really have more 🐶 🍽 .
> Fix: Actually use provideData() in a test, too

- test/DataProvider/AbstractNotNullTestCase.php
- test/DataProvider/AbstractTestCase.php
- test/DataProvider/BlankStringTest.php
- test/DataProvider/BooleanTest.php
- test/DataProvider/ElementsTest.php
- test/DataProvider/InvalidBooleanNotNullTest.php
- test/DataProvider/InvalidBooleanTest.php
- test/DataProvider/InvalidFloatNotNullTest.php
- test/DataProvider/InvalidFloatTest.php
- test/DataProvider/InvalidIntegerNotNullTest.php
- test/DataProvider/InvalidIntegerTest.php
- test/DataProvider/InvalidIntegerishNotNullTest.php
- test/DataProvider/InvalidIntegerishTest.php
- test/DataProvider/InvalidIsoDateNotNullTest.php
- test/DataProvider/InvalidIsoDateTest.php
- test/DataProvider/InvalidNumericNotNullTest.php
- test/DataProvider/InvalidNumericTest.php
- test/DataProvider/InvalidScalarNotNullTest.php
- test/DataProvider/InvalidScalarTest.php
- test/DataProvider/InvalidStringNotNullTest.php
- test/DataProvider/InvalidStringTest.php
- test/DataProvider/InvalidUrlNotNullTest.php
- test/DataProvider/InvalidUrlTest.php
- test/DataProvider/InvalidUuidNotNullTest.php
- test/DataProvider/InvalidUuidTest.php
- test/DataProvider/ScalarTest.php
> Fix: Remove confusing NotNull trait from tests

- src/TestHelper.php
> Fix: Mark methods as final

- test/DataProvider/BlankStringTest.php
- test/DataProvider/BooleanTest.php
- test/DataProvider/ElementsTest.php
- test/DataProvider/InvalidBooleanNotNullTest.php
- test/DataProvider/InvalidBooleanTest.php
- test/DataProvider/InvalidFloatNotNullTest.php
- test/DataProvider/InvalidFloatTest.php
- test/DataProvider/InvalidIntegerNotNullTest.php
- test/DataProvider/InvalidIntegerTest.php
- test/DataProvider/InvalidIntegerishNotNullTest.php
- test/DataProvider/InvalidIntegerishTest.php
- test/DataProvider/InvalidIsoDateNotNullTest.php
- test/DataProvider/InvalidIsoDateTest.php
- test/DataProvider/InvalidNumericNotNullTest.php
- test/DataProvider/InvalidNumericTest.php
- test/DataProvider/InvalidScalarNotNullTest.php
- test/DataProvider/InvalidScalarTest.php
- test/DataProvider/InvalidStringNotNullTest.php
- test/DataProvider/InvalidStringTest.php
- test/DataProvider/InvalidUrlNotNullTest.php
- test/DataProvider/InvalidUrlTest.php
- test/DataProvider/InvalidUuidNotNullTest.php
- test/DataProvider/InvalidUuidTest.php
- test/DataProvider/ScalarTest.php
- test/DataProviderFake.php
- test/Faker/GeneratorTest.php
- test/Faker/Provider/ColorTest.php
- test/TestHelperTest.php
> Fix: Mark tests as final

- README.md
- src/TestHelper.php
- test/DataProvider/AbstractTestCase.php
> Fix: Remove Interface from assertion

- src/TestHelper.php
- test/Asset/Foo.php
- test/TestHelperTest.php
This PR
💁‍♂️ Also adds a missing _explicit_ test!
> Fix: Reduce visibility of assertImplements()

- README.md
> Fix: Add  missing closing brace

- test/DataProvider/InvalidIntegerishNotNullTest.php
- test/DataProvider/InvalidIntegerishTest.php
- test/DataProvider/InvalidIsoDateNotNullTest.php
- test/DataProvider/InvalidIsoDateTest.php
- test/DataProvider/InvalidUrlNotNullTest.php
- test/DataProvider/InvalidUrlTest.php
- test/DataProvider/InvalidUuidNotNullTest.php
- test/DataProvider/InvalidUuidTest.php
> Fix: Use assertion chain in tests

- test/TestHelperTest.php
This PR
Follows #98.
Follows #100.
Follows #107.
> Fix: Add missing tests for assertions

- test/Asset/ChildClass.php
- test/Asset/FinalClass.php
- test/Asset/ImplementedInterface.php
- test/Asset/ImplementingClass.php
- test/Asset/NonFinalClass.php
- test/Asset/NonImplementingClass.php
- test/Asset/ParentClass.php
- test/TestHelperTest.php
> Fix: Create concrete assets

- src/TestHelper.php
- test/Asset/ChildInterface.php
- test/Asset/ParentInterface.php
- test/TestHelperTest.php
> Fix: Make assertExtends() work with interfaces

- src/DataProvider/InvalidBoolean.php
- src/DataProvider/InvalidFloat.php
- src/DataProvider/InvalidInteger.php
- src/DataProvider/InvalidIntegerish.php
- src/DataProvider/InvalidString.php
- src/DataProvider/Scalar.php
This PR
💁‍♂️ If we don't provide a value for `$nbMaxDecimals`, it will be [randomly created](https://github.com/fzaninotto/Faker/blob/v1.6.0/src/Faker/Provider/Base.php#L107-L109), and may end up being `0`, that is, we'll also end up rounding an actual float with a precision of `0`, and the result will be an integerish number, causing random tests to fail, because an integerish number is provided when we don't expect it to be provided.
For reference, see [`Faker\Provider\Base::randomFloat()`](https://github.com/fzaninotto/Faker/blob/v1.6.0/src/Faker/Provider/Base.php#L105-L122).
> Fix: Make sure we will always round with a precision greater than 0

- .travis.yml
> Fix: Add PHP7.1 to build matrix

- README.md
- src/DataProvider/Truthy.php
- test/DataProvider/TruthyTest.php
> Enhancement: Implement Truthy data provider

- src/TestHelper.php
> Fix: Do not declare getFaker() as static

- .travis.yml
> Fix: Run php-cs-fixer on PHP 5.6

- src/AbstractTestClassTestCase.php
- test/Asset/HalfEmpty/Bar/Baz.php
- test/Asset/HalfEmpty/Foo/Bar.php
- test/Asset/NotClasses/Bars.php
- test/Asset/NotClasses/FooInterface.php
- test/TestClassTest.php
This PR
💁‍♂️ Inspired by [`PhpCsFixer\Tests\ProjectCodeTest`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.0.0/tests/ProjectCodeTest.php), written by @keradus.
> Enhancement: Implement AbstractTestClassTestCase for asserting test classes are abstract or final

- src/AbstractTestClassTestCase.php
- src/DataProvider/InvalidIsoDate.php
- src/DataProvider/InvalidUrl.php
- src/DataProvider/InvalidUuid.php
- src/DataProvider/NotNull.php
- src/Faker/Provider/Color.php
- src/TestHelper.php
- test/DataProvider/BlankStringTest.php
- test/DataProvider/BooleanTest.php
- test/DataProvider/InvalidBooleanNotNullTest.php
- test/DataProvider/InvalidBooleanTest.php
- test/DataProvider/InvalidFloatNotNullTest.php
- test/DataProvider/InvalidFloatTest.php
- test/DataProvider/InvalidIntegerNotNullTest.php
- test/DataProvider/InvalidIntegerTest.php
- test/DataProvider/InvalidNumericNotNullTest.php
- test/DataProvider/InvalidNumericTest.php
- test/DataProvider/InvalidScalarNotNullTest.php
- test/DataProvider/InvalidScalarTest.php
- test/DataProvider/InvalidStringNotNullTest.php
- test/DataProvider/InvalidStringTest.php
- test/DataProvider/ScalarTest.php
- test/TestClassTest.php
- test/TestHelperTest.php
This PR
💁‍♂️ For reference, see 
* https://twitter.com/Ocramius/status/811504929357660160
* http://php.net/manual/en/language.namespaces.faq.php#language.namespaces.faq.shortname2
* http://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/
>Function or constant names that do not contain a backslash like name can be resolved in 2 different ways.
>
>First, the current namespace name is prepended to _name_.
>
>Finally, if the constant or function _name_ does not exist in the current namespace, a global constant or function _name_ is used if it exists.
> Fix: Remove need to resolve global function in current namespace

- src/AbstractTestClassTestCase.php
> Fix: Remove dependency of production code on beberlei/assert

- Makefile
> Fix: Specify phony targets in Makefile

- composer.json
> Fix: Require phpunit/phpunit as actual dependency

- composer.json
> Fix: Make dependency on symfony/finder explicit

- composer.json
- src/AbstractTestClassTestCase.php
- test/Asset/NotClasses/BarTrait.php
- test/Asset/NotEmpty/Bar/Baz.php
- test/Asset/NotEmpty/Foo/Bar.php
- test/TestClassTest.php
> Enhancement: Do not require to specify PSR-4 prefix for asserting classes are abstract or final

- src/TestHelper.php
- test/Asset/WithExclude/Exclude.php
- test/Asset/WithExclude/Exclude/Foo.php
- test/Asset/WithExclude/ExcludeNot/Bar.php
- test/TestHelperTest.php
> Fix: Exclude directories only, not files containing exclude directory in name

- .php_cs
- composer.json
- test/Asset/AnonymousClasses/WithAnonymousClass.php
- test/Asset/AnonymousClasses/with-anonymous-class.php
- test/TestHelperTest.php
This PR
Follows https://github.com/zendframework/zend-file/pull/34.
> Fix: Ignore anonymous classes

- composer.json
This PR
💁‍♂️ It's not actually a dependency, but it makes sense to use it with `phpunit/phpunit`.
> Fix: Do not require, but suggest phpunit/phpunit as a dependency

- src/TestHelper.php
- test/Asset/Message/Foo.php
- test/TestHelperTest.php
> Fix: Allow to pass in plain exception message (without %s)

- src/DataProvider/InvalidBoolean.php
- src/DataProvider/InvalidFloat.php
- src/DataProvider/InvalidInteger.php
- src/DataProvider/InvalidString.php
- src/DataProvider/Scalar.php
> Fix: Ensure that integers are never 0

- Makefile
> Fix: Remove composer.lock in composer target

- README.md
- test/DataProvider/AbstractTestCase.php
- test/Faker/GeneratorTest.php
- test/Faker/Provider/ColorTest.php
- test/TestClassTest.php
- test/TestHelperTest.php
> Fix: Use namespaced PHPUnit test case

- test/DataProvider/BooleanTest.php
- test/DataProvider/InvalidBooleanNotNullTest.php
- test/DataProvider/InvalidBooleanTest.php
- test/DataProvider/InvalidFloatNotNullTest.php
- test/DataProvider/InvalidFloatTest.php
- test/DataProvider/InvalidIntegerNotNullTest.php
- test/DataProvider/InvalidIntegerTest.php
- test/DataProvider/InvalidIntegerishTest.php
- test/DataProvider/InvalidIsoDateNotNullTest.php
- test/DataProvider/InvalidIsoDateTest.php
- test/DataProvider/InvalidScalarNotNullTest.php
- test/DataProvider/InvalidScalarTest.php
- test/DataProvider/InvalidStringNotNullTest.php
- test/DataProvider/InvalidStringTest.php
- test/DataProvider/InvalidUrlNotNullTest.php
- test/DataProvider/InvalidUrlTest.php
- test/DataProvider/InvalidUuidNotNullTest.php
- test/DataProvider/InvalidUuidTest.php
- test/DataProvider/ScalarTest.php
> Fix: Streamline test method names

- test/DataProvider/InvalidIntegerishNotNullTest.php
- test/DataProvider/InvalidIntegerishTest.php
- test/DataProvider/InvalidIsoDateNotNullTest.php
- test/DataProvider/InvalidIsoDateTest.php
- test/DataProvider/InvalidUrlNotNullTest.php
- test/DataProvider/InvalidUrlTest.php
- test/DataProvider/InvalidUuidNotNullTest.php
- test/DataProvider/InvalidUuidTest.php
> Fix: Do not use deprecated Assert\that()

- src/DataProvider/AbstractDataProvider.php
- src/DataProvider/InvalidBoolean.php
- src/DataProvider/InvalidFloat.php
- src/DataProvider/InvalidInteger.php
- src/DataProvider/InvalidIntegerish.php
- src/DataProvider/InvalidIsoDate.php
- src/DataProvider/InvalidNumeric.php
- src/DataProvider/InvalidScalar.php
- src/DataProvider/InvalidString.php
- src/DataProvider/Scalar.php
- src/DataProvider/Truthy.php
> Fix: Extract methods to avoid repetition

- src/DataProvider/DataProviderInterface.php
- src/TestHelper.php
- test/DataProviderFake.php
- test/TestHelperTest.php
This PR
Blocks #161.
💁‍♂️ Not sure what the idea was, it's not used.
> Fix: Remove support for traversable values

- test/TestHelperTest.php
> Fix: Remove unused method

- src/TestHelper.php
- test/TestHelperTest.php
> Fix: Actually use key when providing data

- src/DataProvider/AbstractDataProvider.php
> Fix: Ensure we never end up with 0 unless we want to

- src/DataProvider/AbstractDataProvider.php
> Fix: Use at least 1 decimal

- src/TestHelper.php
> Fix: Use canonical path in assertClassesSatisfy()

- README.md
- src/TestHelper.php
- test/TestHelperTest.php
This PR
Returns a cartesian product of given DataProviders such that given `[1,2]` and `[3,4]` it will return 
```
[ 
[1,3],
[1,4],
[2,3],
[2,4]
]
```
Useful when you need to test combination of data!
> Enhancement: Add provideCombinedDataFrom()
